---
title: Caylia Chaiken Music Studio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
author: Caylia Chaiken
locale: en
title_separator: "-"
name: Caylia Chaiken Music Studio
description: Music lessons in Marin County
url: 
baseurl: 
repository: avelingrayorg/ccms
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
