---
title: Caylia Chaiken Music Studio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    description:
    testimonial:
      text:
      name:
      avatar:
author: Caylia Chaiken
locale: en
title_separator: "-"
name: Caylia Chaiken Music Studio
description: Music lessons in Marin County
social:
  name: Caylia Chaiken
  links:
  - https://www.yelp.com/biz/caylia-chaiken-music-studio-mill-valley
  - https://www.youtube.com/channel/UCa56OJaXhqQN9ei7iiYszEg/videos
  - https://chaikenmusic.bandcamp.com/
  - https://www.facebook.com/Caylia-Chaiken-Music-Studio-200060653385853/
url: 
baseurl: 
repository: avelingrayorg/ccms
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
